package com.pool.spring.model;

// Generated May 28, 2015 5:38:28 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Points generated by hbm2java
 */
@Entity
@Table(name = "points", catalog = "carpool")
public class Points implements java.io.Serializable {

	private String pointId;
	private float latitude;
	private float longitude;
	private int pointOrder;
	private String carPoolId;

	public Points() {
	}

	public Points(String pointId, float latitude, float longitude,
			int pointOrder, String carPoolId) {
		this.pointId = pointId;
		this.latitude = latitude;
		this.longitude = longitude;
		this.pointOrder = pointOrder;
		this.carPoolId = carPoolId;
	}

	@Id
	@Column(name = "pointId", unique = true, nullable = false, length = 100)
	public String getPointId() {
		return this.pointId;
	}

	public void setPointId(String pointId) {
		this.pointId = pointId;
	}

	@Column(name = "latitude", nullable = false, precision = 5, scale = 3)
	public float getLatitude() {
		return this.latitude;
	}

	public void setLatitude(float latitude) {
		this.latitude = latitude;
	}

	@Column(name = "longitude", nullable = false, precision = 5, scale = 3)
	public float getLongitude() {
		return this.longitude;
	}

	public void setLongitude(float longitude) {
		this.longitude = longitude;
	}

	@Column(name = "Point_order", nullable = false)
	public int getPointOrder() {
		return this.pointOrder;
	}

	public void setPointOrder(int pointOrder) {
		this.pointOrder = pointOrder;
	}

	@Column(name = "car_pool_id", nullable = false, length = 2000)
	public String getCarPoolId() {
		return this.carPoolId;
	}

	public void setCarPoolId(String carPoolId) {
		this.carPoolId = carPoolId;
	}

}
