package com.pool.spring.model;

// Generated May 28, 2015 5:38:28 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * PoolSubscription generated by hbm2java
 */
@Entity
@Table(name = "pool_subscription", catalog = "carpool")
public class PoolSubscription implements java.io.Serializable {

	private String subscriptionId;
	private String carPoolId;
	private String travellerId;

	public PoolSubscription() {
	}

	public PoolSubscription(String subscriptionId, String carPoolId) {
		this.subscriptionId = subscriptionId;
		this.carPoolId = carPoolId;
	}

	public PoolSubscription(String subscriptionId, String carPoolId,
			String travellerId) {
		this.subscriptionId = subscriptionId;
		this.carPoolId = carPoolId;
		this.travellerId = travellerId;
	}

	@Id
	@Column(name = "subscriptionId", unique = true, nullable = false, length = 100)
	public String getSubscriptionId() {
		return this.subscriptionId;
	}

	public void setSubscriptionId(String subscriptionId) {
		this.subscriptionId = subscriptionId;
	}

	@Column(name = "car_pool_id", nullable = false, length = 200)
	public String getCarPoolId() {
		return this.carPoolId;
	}

	public void setCarPoolId(String carPoolId) {
		this.carPoolId = carPoolId;
	}

	@Column(name = "traveller_id", length = 200)
	public String getTravellerId() {
		return this.travellerId;
	}

	public void setTravellerId(String travellerId) {
		this.travellerId = travellerId;
	}

}
