package com.pool.spring.model;

// Generated May 28, 2015 5:38:28 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Users generated by hbm2java
 */
@Entity
@Table(name = "users", catalog = "carpool")
public class Users implements java.io.Serializable {

	private String userId;
	private String passwd;
	private String username;
	private String email;
	private String firstName;
	private String lastName;
	private String address;
	private String city;
	private Integer pin;
	private String state;
	private String officeAddress;
	private String gender;
	private Set carpools = new HashSet(0);
	private Set vehicles = new HashSet(0);

	public Users() {
	}

	public Users(String userId, String email) {
		this.userId = userId;
		this.email = email;
	}

	public Users(String userId, String passwd, String username, String email,
			String firstName, String lastName, String address, String city,
			Integer pin, String state, String officeAddress, String gender,
			Set carpools, Set vehicles) {
		this.userId = userId;
		this.passwd = passwd;
		this.username = username;
		this.email = email;
		this.firstName = firstName;
		this.lastName = lastName;
		this.address = address;
		this.city = city;
		this.pin = pin;
		this.state = state;
		this.officeAddress = officeAddress;
		this.gender = gender;
		this.carpools = carpools;
		this.vehicles = vehicles;
	}

	@Id
	@Column(name = "UserId", unique = true, nullable = false, length = 100)
	public String getUserId() {
		return this.userId;
	}

	public void setUserId(String userId) {
		this.userId = userId;
	}

	@Column(name = "passwd")
	public String getPasswd() {
		return this.passwd;
	}

	public void setPasswd(String passwd) {
		this.passwd = passwd;
	}

	@Column(name = "username")
	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	@Column(name = "email", nullable = false)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "First_Name")
	public String getFirstName() {
		return this.firstName;
	}

	public void setFirstName(String firstName) {
		this.firstName = firstName;
	}

	@Column(name = "Last_Name")
	public String getLastName() {
		return this.lastName;
	}

	public void setLastName(String lastName) {
		this.lastName = lastName;
	}

	@Column(name = "Address")
	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	@Column(name = "City")
	public String getCity() {
		return this.city;
	}

	public void setCity(String city) {
		this.city = city;
	}

	@Column(name = "PIN")
	public Integer getPin() {
		return this.pin;
	}

	public void setPin(Integer pin) {
		this.pin = pin;
	}

	@Column(name = "state")
	public String getState() {
		return this.state;
	}

	public void setState(String state) {
		this.state = state;
	}

	@Column(name = "office_address")
	public String getOfficeAddress() {
		return this.officeAddress;
	}

	public void setOfficeAddress(String officeAddress) {
		this.officeAddress = officeAddress;
	}

	@Column(name = "Gender", length = 2)
	public String getGender() {
		return this.gender;
	}

	public void setGender(String gender) {
		this.gender = gender;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "users")
	public Set getCarpools() {
		return this.carpools;
	}

	public void setCarpools(Set carpools) {
		this.carpools = carpools;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "users")
	public Set getVehicles() {
		return this.vehicles;
	}

	public void setVehicles(Set vehicles) {
		this.vehicles = vehicles;
	}

}
